
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author federico
 */
public class ConsultaPorRubro extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel(){
        public boolean isCellEditable(){
            return false;
        }
    };
    
    public ConsultaPorRubro() {
        initComponents();
        cargarCombo();
        cargarCabecera();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTituloRubro = new javax.swing.JLabel();
        lbRubro = new javax.swing.JLabel();
        comboBoxRubro = new javax.swing.JComboBox<>();
        lbIconRubro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableConsultaPorRubro = new javax.swing.JTable();

        setClosable(true);
        setResizable(true);

        lbTituloRubro.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lbTituloRubro.setText("Consulta por Rubro");

        lbRubro.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lbRubro.setText("Rubro:");

        comboBoxRubro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxRubro.addActionListener(this::comboBoxRubroActionPerformed);

        lbIconRubro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabajopracticoseis/Imagen/icons8-magnifying-glass-tilted-right-48.png"))); // NOI18N

        tableConsultaPorRubro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableConsultaPorRubro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbRubro)
                                .addGap(18, 18, 18)
                                .addComponent(comboBoxRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(lbTituloRubro)))
                        .addGap(18, 18, 18)
                        .addComponent(lbIconRubro))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbIconRubro)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTituloRubro)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbRubro)
                            .addComponent(comboBoxRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxRubroActionPerformed
        int index = comboBoxRubro.getSelectedIndex();
        
        if(index > 0){
            modelo.setRowCount(0);
            for(Producto p: MenuGeneral.listaProductos){
                if(p.getRubro().equals(comboBoxRubro.getSelectedItem())){
                    modelo.addRow(new Object[]{
                        p.getCodigo(),
                        p.getDescripcion(),
                        p.getPrecio(),
                        p.getRubro(),
                        p.getStock()
                    });
                }
            }
        } else if (index == 0){
            cargarTabla();
        }
    }//GEN-LAST:event_comboBoxRubroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxRubro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbIconRubro;
    private javax.swing.JLabel lbRubro;
    private javax.swing.JLabel lbTituloRubro;
    private javax.swing.JTable tableConsultaPorRubro;
    // End of variables declaration//GEN-END:variables

    private void cargarCombo(){
        comboBoxRubro.removeAllItems();
        comboBoxRubro.addItem("Seleccione una categoria");
        comboBoxRubro.addItem("COMESTIBLE");
        comboBoxRubro.addItem("LIMPIEZA");
        comboBoxRubro.addItem("PERFUMERIA");
    }
    
    private void cargarCabecera(){
        modelo.addColumn("Código");
        modelo.addColumn("Descripción");
        modelo.addColumn("Precio");
        modelo.addColumn("Rubro");
        modelo.addColumn("Stock");
        
        tableConsultaPorRubro.setModel(modelo);
    }
    
    private void cargarTabla(){
        modelo.setRowCount(0);
        
        for(Producto p: MenuGeneral.listaProductos){
            modelo.addRow(new Object[]{
                p.getCodigo(),
                p.getDescripcion(),
                p.getPrecio(),
                p.getRubro(),
                p.getStock()
            });
        }
    }
}
