
import java.util.TreeSet;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hideko
 */
public class MenuGeneral extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuGeneral.class.getName());

    public static TreeSet<Producto> listaProductos = new TreeSet<>();
    /**
     * Creates new form MenuGeneral
     */
    public MenuGeneral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDPescritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMgestProduct = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMconsulta = new javax.swing.JMenuItem();
        jmiConsultaporprecio = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDPescritorioLayout = new javax.swing.GroupLayout(jDPescritorio);
        jDPescritorio.setLayout(jDPescritorioLayout);
        jDPescritorioLayout.setHorizontalGroup(
            jDPescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jDPescritorioLayout.setVerticalGroup(
            jDPescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jMenu1.setText("Administracion");

        jMgestProduct.setText("Gestionar Productos");
        jMgestProduct.addActionListener(this::jMgestProductActionPerformed);
        jMenu1.add(jMgestProduct);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");

        jMconsulta.setText("Consulta por Nombre");
        jMconsulta.addActionListener(this::jMconsultaActionPerformed);
        jMenu2.add(jMconsulta);

        jmiConsultaporprecio.setText("Consulta por Precio");
        jmiConsultaporprecio.addActionListener(this::jmiConsultaporprecioActionPerformed);
        jMenu2.add(jmiConsultaporprecio);

        jMenuItem2.setText("Consulta por Rubro");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPescritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPescritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMconsultaActionPerformed
        jDPescritorio.removeAll();
        jDPescritorio.repaint();
        ConsultaPorNombre cPN = new ConsultaPorNombre();
        cPN.setVisible(true);
        jDPescritorio.add(cPN);
    }//GEN-LAST:event_jMconsultaActionPerformed

    private void jmiConsultaporprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultaporprecioActionPerformed
        // TODO add your handling code here:
        jDPescritorio.removeAll();
        jDPescritorio.repaint();
        ConsultaPorPrecio cpp = new ConsultaPorPrecio();
        cpp.setVisible(true);
        jDPescritorio.add(cpp);
        cpp.moveToFront();
        
    }//GEN-LAST:event_jmiConsultaporprecioActionPerformed

    private void jMgestProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMgestProductActionPerformed
        jDPescritorio.removeAll();
        jDPescritorio.repaint();
        VistaProductos vp = new VistaProductos();
        vp.setVisible(true);
        jDPescritorio.add(vp);
        jDPescritorio.moveToFront(vp);
    }//GEN-LAST:event_jMgestProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuGeneral().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDPescritorio;
    private javax.swing.JMenuItem jMconsulta;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMgestProduct;
    private javax.swing.JMenuItem jmiConsultaporprecio;
    // End of variables declaration//GEN-END:variables
}
